spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  application:
    name: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_new?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
